
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int igualigual = 26;
  public static final int res_continue = 15;
  public static final int res_if = 7;
  public static final int UMINUS = 48;
  public static final int UPLUS = 49;
  public static final int coma = 24;
  public static final int igual = 27;
  public static final int ternario = 34;
  public static final int l_llave = 20;
  public static final int res_break = 14;
  public static final int r_llave = 21;
  public static final int res_case = 12;
  public static final int r_parent = 23;
  public static final int numero = 44;
  public static final int res_while = 9;
  public static final int res_default = 13;
  public static final int menos = 29;
  public static final int menor = 38;
  public static final int EOF = 0;
  public static final int mas = 28;
  public static final int error = 1;
  public static final int doble = 45;
  public static final int mayor = 36;
  public static final int or = 41;
  public static final int menorigual = 37;
  public static final int res_false = 3;
  public static final int res_do = 17;
  public static final int por = 30;
  public static final int dospuntos = 43;
  public static final int id = 46;
  public static final int potencia = 31;
  public static final int res_true = 4;
  public static final int res_for = 10;
  public static final int l_corchete = 18;
  public static final int res_null = 2;
  public static final int mayorigual = 35;
  public static final int diferente = 39;
  public static final int not = 42;
  public static final int and = 40;
  public static final int puntocoma = 25;
  public static final int res_return = 16;
  public static final int modular = 32;
  public static final int res_else = 8;
  public static final int div = 33;
  public static final int res_function = 5;
  public static final int l_parent = 22;
  public static final int res_in = 6;
  public static final int cadena = 47;
  public static final int res_switch = 11;
  public static final int r_corchete = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "res_null",
  "res_false",
  "res_true",
  "res_function",
  "res_in",
  "res_if",
  "res_else",
  "res_while",
  "res_for",
  "res_switch",
  "res_case",
  "res_default",
  "res_break",
  "res_continue",
  "res_return",
  "res_do",
  "l_corchete",
  "r_corchete",
  "l_llave",
  "r_llave",
  "l_parent",
  "r_parent",
  "coma",
  "puntocoma",
  "igualigual",
  "igual",
  "mas",
  "menos",
  "por",
  "potencia",
  "modular",
  "div",
  "ternario",
  "mayorigual",
  "mayor",
  "menorigual",
  "menor",
  "diferente",
  "and",
  "or",
  "not",
  "dospuntos",
  "numero",
  "doble",
  "id",
  "cadena",
  "UMINUS",
  "UPLUS"
  };
}

